name: ci

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker
        run: |
          echo "DOCKER_CLI_EXPERIMENTAL=enabled" >> $env:GITHUB_ENV
          docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

      - name: Build and push
        run: |
          docker build --platform windows/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest .
          docker build --platform linux/amd64 -t ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest .
          docker build --platform linux/arm64 -t ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest .
          docker build --platform linux/arm/v7 -t ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest

      - name: Push image
        run: |
          docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_TOKEN }}
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/clockbox:latest
